name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore OrderManagementApi.Tests/OrderManagementApi.Tests.csproj

      - name: Build
        run: dotnet build OrderManagementApi.Tests/OrderManagementApi.Tests.csproj --configuration Release

      - name: Run tests
        run: dotnet test OrderManagementApi.Tests/OrderManagementApi.Tests.csproj --configuration Release --no-build